/* Generates one inline SVG QR per deployed project into assets/js/qr.js.
   Build-time only — the site itself ships no QR library.
   Run: node scripts/make-qr.mjs */
import QRCode from 'qrcode';
import { writeFileSync } from 'node:fs';
import { projects } from '../assets/js/data.js';

const live = projects.filter((p) => p.deployUrl || p.site);

/* `currentColor` on the modules lets the code re-tint with the active persona
   instead of shipping a separate image per theme. */
async function toSvg(url) {
  const svg = await QRCode.toString(url, {
    type: 'svg',
    errorCorrectionLevel: 'M',
    margin: 2,
    color: { dark: '#000000', light: '#0000' },
  });
  return svg
    .replace(/<\?xml.*?\?>/s, '')
    .replace(/<!DOCTYPE.*?>/s, '')
    .replace(/fill="#000000"/g, 'fill="currentColor"')
    .replace(/stroke="#000000"/g, 'stroke="currentColor"')
    .replace(/width="[^"]*"\s*height="[^"]*"/, 'width="100%" height="100%"')
    .replace(/\s+/g, ' ')
    .trim();
}

const entries = [];
for (const p of live) {
  entries.push(`  ${JSON.stringify(p.name)}: ${JSON.stringify(await toSvg(p.deployUrl || p.site))},`);
  console.log(`${p.name.padEnd(18)} -> ${p.deployUrl || p.site}`);
}

writeFileSync(
  'assets/js/qr.js',
  `/* GENERATED by scripts/make-qr.mjs — do not edit.\n   One QR per deployed project, tinted with currentColor. */\nexport const qr = {\n${entries.join('\n')}\n};\n`,
);
console.log(`\nwrote assets/js/qr.js (${live.length} codes)`);
